### ISSUE TITLE
Is DriveGitRepo being maintained?

### ISSUE THREAD

**Issue by wks335github** [lukegeorg/DriveGitRepo#1]
This would be very useful, but oauth2client is deprecated and I couldn't get it to work with
the new credential.json.  It complains about module_name = data['_module']  Key error.

**Comment by lukegeorg** [comment]
Hi wks335github,

Glad to hear this, this project is in fact currently not maintained. I had a look at the oauth2client replacement, but it will require some work to perform the migration. At this time I don't have the time to look into it.

Volunteers are more than welcome!

Cheers

**Comment by lukegeorg** [comment]
Hi wks335github,

Glad to hear, I replaced oauth2client with the new version of the API as explained here https://developers.google.com/drive/api/v3/quickstart/python.

It should work now

**Comment by wks335github** [comment]
Thank you very much, I will try it out.
